name: flutter_clean_mvvm
description: "Proyecto de estructuración de aplicaciones Flutter con Clean Architecture, MVVM, Bloc y Get It"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  dio: ^5.7.0
  get_it: ^7.2.0
  go_router: ^14.2.5
  injectable: ^2.4.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  fpdart: ^1.1.1
  safe_extensions: ^1.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^3.0.0
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
